name: breakpoint
description: A Flutter plugin to calculate the material design breakpoints.
version: 1.1.0-nullsafety.0
authors:
 - Flutter Community <community@flutter.zone>
 - Rody Davis <rody.davis.jr@gmail.com>
maintainer: Rody Davis (@rodydavis)
homepage: https://github.com/rodydavis/plugins
issue_tracker: https://github.com/fluttercommunity/breakpoint

environment:
  sdk: '>=2.12.0-259.8.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  
